version: 2.1
orbs:
  android: circleci/android@1.0.3
jobs:
  build-and-test:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - android/run-tests:
          test-command: ./gradlew simpson_viewerDebug
workflows:
  testrunner:
    jobs:
      - build-and-test
